name: Santa says test test test means the bad year is finally
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: run the pytest suite
        run: |
          pytest
